---
- name: Ensure syslog dirs
  file:
    path: "{{ item }}"
    mode: 0755
    owner: root
    group: root
    state: directory
  with_items:
    - "{{ syslog_ca_dir }}"
    - "{{ syslog_cert_dir }}"
    - "{{ syslog_key_dir }}"
    - "{{ syslog_dir }}/conf.d"
    - "{{ syslog_crl_dir }}"

- name: Copy CA certificate to the host
  copy:
    src: "{{ local_ca_cert_dir }}/{{ ca_cert_name }}"
    dest: "{{ syslog_ca_dir }}/{{ ca_cert_name }}"
    mode: 0644
    owner: root
    group: root
  when: push_ca_cert
  register: ca_cert

- name: Client {{ ansible_default_ipv4.address }} | Calculate cacert hash
  command: openssl x509 -noout -hash -in {{ syslog_ca_dir }}/{{ ca_cert_name }}
  register: cacert_hash
  changed_when: false
  when: push_ca_cert

- name: Client {{ ansible_default_ipv4.address }} | Create cacert link
  file:
    state: link
    src: "{{ syslog_ca_dir }}/{{ ca_cert_name }}"
    path: "{{ syslog_ca_dir }}/{{ cacert_hash.stdout }}.0"
  when: push_ca_cert
