---
- name: TLS for SYSLOG | Keys creation | Create Client Key
  shell: openssl req -nodes -new -x509 -keyout "private/{{host}}key.pem" -out "private/{{host}}req.pem" -days 365 \
    -config openssl.cnf \
    -subj /C={{client.country}}/ST={{client.province}}/L={{client.city}}/O={{client.org}}/OU={{client.ou}}/CN={{host}}/emailAddress={{client.email}}
  args:
    chdir: "{{ca_dir_path}}"
    creates: "private/{{ host }}req.pem"
    creates: "private/{{ host }}key.pem"

- name: TLS for SYSLOG | Keys creation | Create Client CSR
  shell: "openssl x509 -x509toreq -in private/{{ host }}req.pem -signkey private/{{host}}key.pem -out {{ host }}tmp.pem"
  args:
    chdir: "{{ca_dir_path}}"
    creates: "{{ host }}tmp.pem"

- name: TLS for SYSLOG | Keys creation | Sign Client Cert
  shell: "openssl ca -batch -config openssl.cnf -policy policy_anything -passin pass:{{ca_password}} -out certs/{{ host }}cert.pem -infiles {{ host }}tmp.pem"
  args:
    chdir: "{{ca_dir_path}}"
    creates: "certs/{{ host }}cert.pem"

- name: TLS for SYSLOG | Keys creation | Remove Client CSR
  file:
    path: "{{ ca_dir_path }}/{{ host }}tmp.pem"
    state: absent
