---
- name: Install latest version of OpenSSL
  package:
    name: openssl
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Install latest version of syslog-ng
  package:
    name: syslog-ng
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Install python requirments
  apt:
    name: python3-pip

- name: Install openssl requirments
  pip:
    name: cryptography>=1.3
