---
- name: Install latest version of OpenSSL
  package:
    name: openssl
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Add an Apt signing key, uses whichever key is at the URL
  become: true
  become_user: root
  apt_key:
    url: https://ose-repo.syslog-ng.com/apt/syslog-ng-ose-pub.asc
  when: spec_repo
  tags:
    - install_syslog-ng

- name: Add specified repository into sources list
  become: true
  become_user: root
  apt_repository:
    repo: deb https://ose-repo.syslog-ng.com/apt/ stable ubuntu-focal
  when: spec_repo
  tags:
    - install_syslog-ng

- name: Install latest version of syslog-ng
  package:
    name: syslog-ng
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  tags:
    - install_syslog-ng

- name: Install python requirments
  apt:
    name: python3-pip

- name: Install openssl requirments
  pip:
    name: cryptography>=1.3
