---
- name: TLS for SYSLOG | Checks | Check provided options
  import_tasks: _prechecks.yml
  tags: ['checks']

- name: TLS for SYSLOG | Installation | Prepare OpenSSL CA
  import_tasks: prepare_openssl_ca.yml
  tags: ['openssl_ca_prepare']

- name: TLS for SYSLOG | CA creation | Setup OpenSSL CA
  import_tasks: setup_openssl_ca.yml
  tags: ['openssl_ca_setup']
