---
- name: Check provided options
  import_tasks: _prechecks.yml

- name: Install requirments
  import_tasks: install_requirements.yml

- name: SYSLOG Server TLS | Copy keys and certs
  import_tasks: copy_files.yml

- name: Install syslog-ng server templates
  include_tasks: install_syslog_server_templates.yml
