---
- name: TLS for SYSLOG | Configuration | Copy to openssl config
  file:
    src: "/etc/ssl/openssl.cnf openssl.cnf"
    dest: "{{ca_dir_path}}/openssl.cnf"

- name: TLS for SYSLOG | Configuration | Change default CA dir
  lineinfile:
    path: "{{ca_dir_path}}/openssl.cnf"
    regexp: './demoCA'
    line: 'dir             = .'
